version: '3'

services:
  dbpostgres:
    image: postgres
    ports: 
      - '5432:5432'
    container_name: funimationdb
    volumes: 
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: TorontoTOKYO2
      POSTGRES_DB: funimationapi


volumes: 
  postgres-disk: